create table attivita (
    id          number 
                generated by default on null as identity
                constraint attivita_id_pk primary key,
    progetto    varchar2(20 char) 
                default on null 'A' 
                not null 
                constraint attivita_progetto_ck check ( progetto in ('val1','val2') )
);