-- drop objects
drop table d07_tipo_prodotto cascade constraints;
drop table d07_prodotto cascade constraints;
drop table d07_cliente cascade constraints;
drop table d07_fornitore cascade constraints;
drop table d07_acquisto cascade constraints;
drop table d07_vendita cascade constraints;

-- create tables
create table d07_tipo_prodotto (
    id                             number generated by default on null as identity 
                                   constraint d07_tipo_prodotto_id_pk primary key,
    tipo_prodotto                  varchar2(50 char)
                                   constraint d07_tipo_prodot_tipo_prodo_unq unique not null,
    gruppo                         varchar2(50 char) not null
)
;

create table d07_prodotto (
    id                             number generated by default on null as identity 
                                   constraint d07_prodotto_id_pk primary key,
    tipo_prodotto_id               number
                                   constraint d07_prodotto_tipo_prodotto_fk
                                   references d07_tipo_prodotto not null,
    prodotto                       varchar2(50 char) not null,
    prezzo_acquisto                number not null,
    prezzo_vendita                 number not null
)
;

-- table index
create index d07_prodotto_i1 on d07_prodotto (tipo_prodotto_id);

create table d07_cliente (
    id                             number generated by default on null as identity 
                                   constraint d07_cliente_id_pk primary key,
    cliente                        varchar2(50 char)
                                   constraint d07_cliente_cliente_unq unique not null,
    zona                           varchar2(10 char) not null
)
;

create table d07_fornitore (
    id                             number generated by default on null as identity 
                                   constraint d07_fornitore_id_pk primary key,
    fornitore                      varchar2(50 char)
                                   constraint d07_fornitore_fornitore_unq unique not null,
    zona                           varchar2(50 char) not null
)
;

create table d07_acquisto (
    id                             number generated by default on null as identity 
                                   constraint d07_acquisto_id_pk primary key,
    fornitore_id                   number
                                   constraint d07_acquisto_fornitore_id_fk
                                   references d07_fornitore not null,
    prodotto_id                    number
                                   constraint d07_acquisto_prodotto_id_fk
                                   references d07_prodotto not null,
    data                           date not null,
    quantita                       number not null
)
;

-- table index
create index d07_acquisto_i1 on d07_acquisto (fornitore_id);
create index d07_acquisto_i132 on d07_acquisto (prodotto_id);

create table d07_vendita (
    id                             number generated by default on null as identity 
                                   constraint d07_vendita_id_pk primary key,
    cliente_id                     number
                                   constraint d07_vendita_cliente_id_fk
                                   references d07_cliente not null,
    prodotto_id                    number
                                   constraint d07_vendita_prodotto_id_fk
                                   references d07_prodotto not null,
    data                           date not null,
    quantita                       number not null
)
;

-- table index
create index d07_vendita_i1 on d07_vendita (cliente_id);
create index d07_vendita_i182 on d07_vendita (prodotto_id);

-- load data
 
-- Generated by Quick SQL Venerdì Aprile 13, 2023  05:50:30
 
/*
tipo prodotto
  tipo prodotto vc50 /nn /unique
  gruppo vc50 /nn

prodotto
  prodotto vc50 /nn
  prezzo acquisto num /nn
  prezzo vendita num /nn
  tipo_prodotto_id /nn

cliente
  cliente vc50 /nn /unique
  zona vc10 /nn

fornitore
  fornitore vc50 /nn /unique
  zona vc50 /nn

acquisto
  data d /nn
  fornitore_id /nn
  prodotto_id /nn
  quantita num /nn

vendita
  data d /nn
  cliente_id  /nn
  prodotto_id /nn
  quantita num /nn

# settings = { prefix: "d07", onDelete: "RESTRICT", semantics: "CHAR", drop: true, language: "EN", APEX: true }
*/