drop table d13_tipo_documento cascade constraints;
drop table d13_documento cascade constraints;
-- create tables

create table d13_tipo_documento (
    id                number generated by default on null as identity
                      constraint d13_tipo_documento_id_pk primary key,
    tipo_documento    varchar2(20 char)
                      constraint tipo_documento_tipo_documento_unq unique not null
);


create table d13_documento (
    id                   number generated by default on null as identity
                         constraint d13_documento_id_pk primary key,
    tipo_documento_id    number                         constraint d13_documento_tipo_documento_id_fk
                         references d13_tipo_documento,
    codice               varchar2(20 char)
                         constraint documento_codice_unq unique not null,
    data_documento       date not null,
    categoria            varchar2(100 char)
);

-- table index
create index d13_documento_i1 on d13_documento (tipo_documento_id);



-- Generated by Quick SQL 1.2.9 03/03/2025, 09:23:56

/*
tipo documento 
  tipo documento vc20 /nn  /unique
  documento
    codice vc20 /nn /unique
    data documento date /nn
    categoria vc100




 Non-default options:
# settings = {"apex":true,"db":"19c","drop":true,"prefix":"d13","pk":"IDENTITY"}

*/