drop table d13_tipo_documento cascade constraints;
drop package d13_tipo_documento_api;
drop table d13_documento cascade constraints;
drop package d13_documento_api;
-- create tables

create table d13_tipo_documento (
    id                number generated by default on null as identity
                      constraint d13_tipo_documento_id_pk primary key,
    tipo_documento    varchar2(20 char)
                      constraint tipo_documento_tipo_documento_unq unique not null
);


create table d13_documento (
    id                   number generated by default on null as identity
                         constraint d13_documento_id_pk primary key,
    tipo_documento_id    number                         constraint d13_documento_tipo_documento_id_fk
                         references d13_tipo_documento,
    codice               varchar2(20 char)
                         constraint documento_codice_unq unique not null,
    data_documento       date not null,
    categoria            varchar2(100 char)
);

-- table index
create index d13_documento_i1 on d13_documento (tipo_documento_id);



-- APIs
create or replace package d13_tipo_documento_api
is

    procedure get_row (
        p_id        in  number,
        p_tipo_documento   out  varchar2
    );

    procedure insert_row (
        p_id        in  number default null,
        p_tipo_documento    in  varchar2 default null
    );

    procedure update_row (
        p_id        in  number default null,
        p_tipo_documento    in  varchar2 default null
    );

    procedure delete_row (
        p_id              in number
    );
end d13_tipo_documento_api;
/

create or replace package body d13_tipo_documento_api
is

    procedure get_row (
        p_id        in  number,
        p_tipo_documento   out  varchar2
    )
    is 
    begin 
        for c1 in (select * from d13_tipo_documento where id = p_id) loop 
            p_tipo_documento := c1.tipo_documento;

        end loop;

    end get_row;
 
     procedure insert_row (
        p_id        in  number default null,
        p_tipo_documento    in  varchar2 default null
    )
    is 
    begin 
        insert into d13_tipo_documento ( 
            id,
            tipo_documento
        ) values ( 
            p_id,
            p_tipo_documento
        );
    end insert_row;
 
     procedure update_row (
        p_id        in  number default null,
        p_tipo_documento    in  varchar2 default null
    )
    is 
    begin 
        update  d13_tipo_documento set 
            id = p_id,
            tipo_documento = p_tipo_documento
        where id = p_id;
    end update_row;
 
     procedure delete_row (
        p_id              in number
    )
    is
    begin
        delete from d13_tipo_documento where id = p_id;
    end delete_row;
end d13_tipo_documento_api;
/

create or replace package d13_documento_api
is

    procedure get_row (
        p_id        in  number,
        p_tipo_documento_id   out  number,
        p_codice   out  varchar2,
        p_data_documento   out  date,
        p_categoria   out  varchar2
    );

    procedure insert_row (
        p_id        in  number default null,
        p_tipo_documento_id    in  number default null,
        p_codice    in  varchar2 default null,
        p_data_documento    in  date default null,
        p_categoria    in  varchar2 default null
    );

    procedure update_row (
        p_id        in  number default null,
        p_tipo_documento_id    in  number default null,
        p_codice    in  varchar2 default null,
        p_data_documento    in  date default null,
        p_categoria    in  varchar2 default null
    );

    procedure delete_row (
        p_id              in number
    );
end d13_documento_api;
/

create or replace package body d13_documento_api
is

    procedure get_row (
        p_id        in  number,
        p_tipo_documento_id   out  number,
        p_codice   out  varchar2,
        p_data_documento   out  date,
        p_categoria   out  varchar2
    )
    is 
    begin 
        for c1 in (select * from d13_documento where id = p_id) loop 
            p_tipo_documento_id := c1.tipo_documento_id;
            p_codice := c1.codice;
            p_data_documento := c1.data_documento;
            p_categoria := c1.categoria;

        end loop;

    end get_row;
 
     procedure insert_row (
        p_id        in  number default null,
        p_tipo_documento_id    in  number default null,
        p_codice    in  varchar2 default null,
        p_data_documento    in  date default null,
        p_categoria    in  varchar2 default null
    )
    is 
    begin 
        insert into d13_documento ( 
            id,
            tipo_documento_id,
            codice,
            data_documento,
            categoria
        ) values ( 
            p_id,
            p_tipo_documento_id,
            p_codice,
            p_data_documento,
            p_categoria
        );
    end insert_row;
 
     procedure update_row (
        p_id        in  number default null,
        p_tipo_documento_id    in  number default null,
        p_codice    in  varchar2 default null,
        p_data_documento    in  date default null,
        p_categoria    in  varchar2 default null
    )
    is 
    begin 
        update  d13_documento set 
            id = p_id,
            tipo_documento_id = p_tipo_documento_id
,
            codice = p_codice
,
            data_documento = p_data_documento
,
            categoria = p_categoria
        where id = p_id;
    end update_row;
 
     procedure delete_row (
        p_id              in number
    )
    is
    begin
        delete from d13_documento where id = p_id;
    end delete_row;
end d13_documento_api;
/

-- Generated by Quick SQL 1.2.9 03/03/2025, 09:23:06

/*
tipo documento 
  tipo documento vc20 /nn  /unique
  documento
    codice vc20 /nn /unique
    data documento date /nn
    categoria vc100




 Non-default options:
# settings = {"apex":true,"db":"19c","drop":true,"prefix":"d13","pk":"IDENTITY","api":true}

*/